---
title: "Tarea 1"
author: "Erick Verdugo"
date: "2025-04-03"
output:
  html_document: default
  pdf_document: default

---


```{r}
plot(cars)

# Install required packages if they are missing
packages <- c("ggplot2", "tidyverse", "datasauRus", "dplyr")
install_if_missing <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
}
lapply(packages, install_if_missing)


```
```{r}
plot(cars)

library(ggplot2)
library(tidyverse)

```

```{r}
plot(cars)

library(datasauRus)
library(dplyr)

print("Inicio del código")

```


```{r}
plot(cars)

# Summarize dataset
summary_stats <- datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(
    mean_x = mean(x),
    mean_y = mean(y),
    std_dev_x = sd(x),
    std_dev_y = sd(y),
    corr_x_y = cor(x, y)
  )

# Print summary stats
print(summary_stats)

```


```{r}
plot(cars)

# Plot data
ggplot(datasaurus_dozen, aes(x = x, y = y, colour = dataset)) +
  geom_point() +
  theme_void() +
  theme(legend.position = "none") +
  facet_wrap(~dataset, ncol = 3)


```





```{r}
plot(cars)

# Filtrar solo el dataset "wide_lines"
wide_lines_data <- datasaurus_dozen %>% filter(dataset == "slant_up")

# Graficar con línea de regresión
ggplot(wide_lines_data, aes(x = x, y = y)) +
  geom_point(color = "blue", alpha = 0.8) +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  theme_minimal()


```








